### ISSUE TITLE
not working with bigger size file

### ISSUE THREAD

**Issue by permanart** [aws-samples/aws-media-services-simple-vod-workflow#25]
I tried with another mp4 file with bigger size, but the job won't running..

**Comment by prabhatmishra33** [comment]
@permanart you found some solution for this? and what size and duration of files you tried ?

**Comment by ayacoo** [comment]
https://forums.aws.amazon.com/thread.jspa?threadID=222747

"It turns out, I was setting the event as ObjectCreated:Put, whereas I needed to use ObjectCreated:CompleteMultipartUpload. To capture other forms of upload, I settled with ObjectCreated:*"

When creating the trigger, not only PUT is enough. The converter still managed a 10 MB file, but larger files no longer. After that the setting in the trigger had to be set to "ObjectCreated" and it worked.
