### ISSUE TITLE
SCTE35 Ad Markers 

### ISSUE THREAD

**Issue by samueleastdev** [aws-samples/aws-media-services-simple-vod-workflow#3]
Hi All,

Great tutorial but I can seem to find the VANLIFE.m2ts file for testing its not in the git repo?

I get stuck when I get to this section
https://github.com/aws-samples/aws-media-services-simple-vod-workflow/tree/master/6-

After talking on support I believe that SCTE35 Ad Markers need to be inserted into the file itself before upload.

It would be great to have a tutorial on how to do this.

**Comment by aburkleaux-amazon** [comment]
The input file with the SCTE35 Ad Markers is hosted in S3: s3://rodeolabz-us-west-2/vodconsole/VANLIFE.m2ts.  Try using this as the input for the job that detects the SCTE-35 Ad Markers.  

We inserted the SCTE-35 ad markers into the VANLIFE video using [Elemetal Live](https://www.elemental.com/products/aws-elemental-live) (a ground encoder for live video). MediaConvert supports interpreting and responding to ad markers that already exist in the video stream, but not inserting them.  Ad marker insertion is usually done using contribution encoders from a live or broadcast workflow or using ad inserters which can be either hardware or software.  

I looked for open source for ad insertion and didn't find anything.  If anyone knows of an open source solution, please share!

Thanks!
Alex

**Comment by samueleastdev** [comment]
Hi Alex,

That's for the response ;)

Yes, I have spent a while searching for an open source solution for ad marker insertion and can't find anything out there.

I am going to take a look at Element Live see if I can achieve this there seems to be a wide range of ways to deliver ads which can get quite confusing, what I am looking to achieve is create a 24/7 Roku channel I would like to also integrate ads into this setup the videos won't be coming from a production house they will be users videos in mp4 format I was going to stitch them all together over a 24 hour period using Media Convert and encode to HLS output then I though maybe insert ad markers in this process.

Any advice on this would be appreciated

Thanks

**Comment by aburkleaux-amazon** [comment]
Sounds like a cool project.

Does 24/7 mean this is a live streaming channel where end users join the stream at the point in time the playout is at, similar to a traditional broadcast channel?   Or, is it VOD where each user starts the playout at their own timeline? 

Assuming it is live streaming, there are many ways to achieve this workflow, but for the Ad Insertion part, right now, the options I know of are all ground based products. However, you should keep an eye on MediaConvert and MediaLive. MediaConvert is based on [Elemental Server](https://www.elemental.com/products/aws-elemental-server) and MediaLive is based on [Elemental Live](https://www.elemental.com/products/aws-elemental-live). Features from the counterpart ground products are frequently added to the AWS managed services.

**Option 1: Elemental Live → AWS Elemental MediaPackage → Roku**

* Elemental Live - schedules content playout using a featue called input switching, insert ad markers, encode as HLS
* AWS Elemental MediaPackage - origin server for stream from Elemental Live. Elemental Live pushes video to the origin server. The origin server caches the stream and delivers in response to http requests.
* Roku - consumes the live stream and does its thing

**Option 2: Elemental Server (another ground based encoder) → S3 → AWS Elemental MediaLive → AWS Elemental MediaPackage → Roku**

* Elemental Server - stitch and encode as HLS, insert ad markers using ESAM metadata
* S3 - store the video(s)
* AWS Elemental MediaLive - re-encode to to other streaming formats, push to origin
* AWS Elemental MediaPackage - origin server for stream from Elemental Live. Elemental Live pushes video to the origin server. The origin server caches the stream and delivers sements in response to http requests.
* Roku - consumes the live stream and does its thing

For, this option, you would also have VOD assets available in S3 that you could offer to play out on-demand through CloudFront.

**Option 3: Using MediaTailor with MediaLive and MediaPackage and an Ad Decision Server (ADS) that supports the VAST protocol**

This method uses metadata to determine when ads are inserted instead of Ad Markers.  

Thanks!
Alex

**Comment by ma11a26** [comment]
Hi Alex,

I'm currently trying to find some M2TS test content including SCTE-35 marker. By searching in Google I found your S3 link to:  s3://rodeolabz-us-west-2/vodconsole/VANLIFE.m2ts. I'm currently working on a project where I will use an ATEME OTT-encoders. The scope is to find out how SCTE-35 markers can be used for dynamic ad insertion into HLS/DASH end user player.
Can you make this content public available for down loading, because my SW installation is bare metal and not in the AWS?

Thanks!
Markus
